### ISSUE TITLE
Doesn't fetch the coins (Windows)

### ISSUE THREAD

**Issue by 894-572** [joaopsys/AutoChronoGG#9]
I've updated the cloned repository before creating this issue. When running `./chronogg.py "JWT unique identifier"`:

```
2018-10-14 10:52:30 INFO  [root] [get_web_page()] Fetching https://api.chrono.gg/quest/spin <line 69>
Traceback (most recent call last):
  File "C:\WINDOWS\system32\AutoChronoGG\chronogg.py", line 188, in <module>
    main()
  File "C:\WINDOWS\system32\AutoChronoGG\chronogg.py", line 152, in main
    results = get_web_page(POST_URL, GLOBAL_HEADERS, gg_cookie)
  File "C:\WINDOWS\system32\AutoChronoGG\chronogg.py", line 72, in get_web_page
    response = urllib.request.urlopen(request)
  File "C:\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Python37\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python37\lib\http\client.py", line 1270, in _send_request
    self.putheader(hdr, value)
  File "C:\Python37\lib\http\client.py", line 1202, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 30: ordinal not in range(256)
```

**Comment by joaopsys** [comment]
I'm not able to reproduce this. Can you give me some more details? E.g. Python version, how exactly are you running the script? Can you also try doing:

python chronogg.py "token"

**Comment by kamegami13** [comment]
Oddly enough, I was having this issue and changing to single quotes fixed it

**Comment by 894-572** [comment]
> I'm not able to reproduce this. Can you give me some more details? E.g. Python version, how exactly are you running the script? 
`Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32`
>Can you also try doing:
> 
> python chronogg.py "token"

```
2018-10-22 11:54:27 INFO  [root] [get_web_page()] Fetching https://api.chrono.gg/quest/spin <line 69>
2018-10-22 11:54:28 INFO  [root] [get_web_page()] Error processing webpage: HTTP Error 401: Unauthorized <line 81>
2018-10-22 11:54:28 INFO  [root] [main()] An error occurred while fetching results: Expired/invalid authorization token. Terminating... <line 161>
```

**Comment by 894-572** [comment]
@joaopsys I didn't copy the full authorization token, I now see in my command history that there's an [ellipsis](https://en.wikipedia.org/wiki/Ellipsis) `…` character (a single character, not three dots) in the middle. I assumed that double-clicking copies entire strings in Firefox.

**Comment by 894-572** [comment]
@kamegami13
> Oddly enough, I was having this issue and changing to single quotes fixed it

The script gives "Expired/invalid authorization token" error if  the token isn't enclosed in apostrophes (`'`).
```
2018-11-02 22:07:26 INFO  [root] [get_web_page()] Fetching https://api.chrono.gg/quest/spin <line 69>
2018-11-02 22:07:26 INFO  [root] [get_web_page()] Error processing webpage: HTTP Error 401: Unauthorized <line 81>
2018-11-02 22:07:26 INFO  [root] [main()] An error occurred while fetching results: Expired/invalid authorization token. Terminating... <line 161>
```
